repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest --cov --cov-report=term --cov-config=.coveragerc
        language: system
        types: [python]
        pass_filenames: false
        verbose: true
