"""Fix tables3

Revision ID: 8c66241abd45
Revises: 94c57196a9f8
Create Date: 2024-11-28 02:29:08.287301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c66241abd45'
down_revision: Union[str, None] = '94c57196a9f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('articles_user_fkey', 'articles', type_='foreignkey')
    op.create_foreign_key(None, 'articles', 'users', ['user_id'], ['id'])
    op.drop_column('articles', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key('articles_user_fkey', 'articles', 'users', ['user'], ['id'])
    op.drop_column('articles', 'user_id')
    # ### end Alembic commands ###
