"""Fix_tables2

Revision ID: 94c57196a9f8
Revises: 3f24516f60af
Create Date: 2024-11-28 01:06:36.512757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c57196a9f8'
down_revision: Union[str, None] = '3f24516f60af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles', 'users', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'user')
    # ### end Alembic commands ###
