# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Flask application

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
    steps:
    - uses: actions/checkout@v2
    - name: docker compose up
      env:
        COMPOSE_INTERACTIVE_NO_CLI: 1
      run: docker compose up -d
    - name: Check running containers
      run: docker compose ps -a
    - name: Check logs
      run: docker compose logs app
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'
    - name: Create database and load data
      run: docker compose exec app python load_data.py
    - name: Test with pytest
      env:
        COMPOSE_INTERACTIVE_NO_CLI: 1
      run: docker compose exec app pytest
